model: "efficientnet-b0"
training:
  epochs: 30
  batch_size: 45
  lr_schedule:
    start_lr: 1e-3
    max_lr: 1e-2
    end_lr: 1e-7
    warmup_epochs: 3
  optimizer:
    type: "SGD"
    nesterov: true
    momentum: 0.9
    weight_decay: 1e-5